#!/bin/sh
set -o verbose
OUT=../output
emcc -DEMCCHACK  -O2  -o $OUT/xnes.html *.c \
-s EXPORTED_FUNCTIONS="['_main', '_reboot_emulator', '_native_set_joypad_state', '_renderscreen', '_mainloop', '_native_bitmap_pointer']"  || exit 1
python extract_script.py $OUT/xnes.html > $OUT/xnes.html.js || exit 1
rm $OUT/xnes.html || exit 1
cp snesEmu.html $OUT

